import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { afterEach, describe, expect, it } from "vitest";
import { runWithWatcher } from "../../src/reminders/command-runner.js";
const exec = promisify(execFile); const directories: string[] = [];
afterEach(async () => Promise.all(directories.splice(0).map((path) => rm(path, { recursive: true, force: true }))));
describe("runWithWatcher", () => { it("returns the child process exit code and stops the watcher", async () => { const root = await mkdtemp(join(tmpdir(), "commitcraft-run-")); directories.push(root); await exec("git", ["init", "-b", "main"], { cwd: root }); const result = await runWithWatcher(process.execPath, ["-e", "process.exit(7)"], root); expect(result).toBe(7); }); });
